bash: fail early with error message

diff --git a/scripts/fedora-setup b/scripts/fedora-setup
--- a/scripts/fedora-setup
+++ b/scripts/fedora-setup
@@ -1,6 +1,7 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-set -eu
+set -Eeuo pipefail
+trap 'echo "Error at line $LINENO: $BASH_COMMAND"' ERR
 
 has_cmd() {
   command -v "$1" >/dev/null 2>&1
